<?php

/**
 * 天气预报小部件
 */
use backend\extend\modules\BaseModule;
class Module extends BaseModule
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}